name: Docker Image CI

+on:
+  push:
+    branches:
+    - master
+  pull_request:
+    branches:
+    - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the testing Docker image
      run: docker build . --file Dockerfile.test --network host
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checking via homebrew
      run: |
        CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" > /dev/null 2>&1
        brew install python redis > /dev/null 2>&1
        python3 -m pip install tox > /dev/null 2>&1
        python3 -m tox -e py38
